	drop table recorrido_temp;
SET datestyle = dmy;
CREATE TABLE recorrido_temp 
(
PERIODO INTEGER,
ID_USUARIO INTEGER,
FECHA_HORA_RETIRO TIMESTAMP,
ORIGEN_ESTACION INTEGER,
NOMBRE_ORIGEN TEXT,
DESTINO_ESTACION INTEGER,
NOMBRE_DESTINO TEXT,
TIEMPO_USO TEXT,
FECHA_CREACION TEXT
);
\COPY recorrido_temp FROM './recorridos-realizados-2016.csv' csv HEADER DELIMITER ';';